version: '3'

volumes:
  static:

services:
  mysql:
    container_name: equip_mysql
    image: mysql:8
    env_file: envs/equipment.env
    restart: unless-stopped

  backend:
    container_name: equip_django
    env_file: envs/equipment.env
    build:
      context: ..
      dockerfile: docker/dockerfiles/Dockerfile
    volumes:
      - static:/usr/src/app/static
    depends_on:
      - mysql
    restart: unless-stopped

  nginx:
    image: nginx:1.21.6-alpine
    container_name: equip_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static:/data/static
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped