# Generated by Django 4.1.3 on 2023-04-17 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('sn_mask', models.CharField(max_length=50, verbose_name='SN mask')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=50, verbose_name='SN')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipmenttype', verbose_name='Type')),
            ],
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('type', 'sn'), name='type_sn_idx'),
        ),
    ]
